//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartPower.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SmartPower.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ConnectionStateConnected {
            get {
                return ResourceManager.GetString("ConnectionStateConnected", resourceCulture);
            }
        }
        
        internal static string ConnectionStateConnecting {
            get {
                return ResourceManager.GetString("ConnectionStateConnecting", resourceCulture);
            }
        }
        
        internal static string ConnectionStateError {
            get {
                return ResourceManager.GetString("ConnectionStateError", resourceCulture);
            }
        }
        
        internal static string ConnectionStateNotConnected {
            get {
                return ResourceManager.GetString("ConnectionStateNotConnected", resourceCulture);
            }
        }
        
        internal static string ConnectionStatePaired {
            get {
                return ResourceManager.GetString("ConnectionStatePaired", resourceCulture);
            }
        }
        
        internal static string ConnectionStatePairing {
            get {
                return ResourceManager.GetString("ConnectionStatePairing", resourceCulture);
            }
        }
        
        internal static string ConnectionStateVerified {
            get {
                return ResourceManager.GetString("ConnectionStateVerified", resourceCulture);
            }
        }
        
        internal static string ConnectionStateVerifying {
            get {
                return ResourceManager.GetString("ConnectionStateVerifying", resourceCulture);
            }
        }
        
        internal static string ConnectionStateSkipped {
            get {
                return ResourceManager.GetString("ConnectionStateSkipped", resourceCulture);
            }
        }
        
        internal static string title_vin_and_floorplan {
            get {
                return ResourceManager.GetString("title_vin_and_floorplan", resourceCulture);
            }
        }
        
        internal static string enter_or_scan_vin {
            get {
                return ResourceManager.GetString("enter_or_scan_vin", resourceCulture);
            }
        }
        
        internal static string enter_vin {
            get {
                return ResourceManager.GetString("enter_vin", resourceCulture);
            }
        }
        
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        internal static string title_pair_devices {
            get {
                return ResourceManager.GetString("title_pair_devices", resourceCulture);
            }
        }
        
        internal static string select_floorplan {
            get {
                return ResourceManager.GetString("select_floorplan", resourceCulture);
            }
        }
        
        internal static string existing_vin {
            get {
                return ResourceManager.GetString("existing_vin", resourceCulture);
            }
        }
        
        internal static string you_have_already_paired_using_this_vin {
            get {
                return ResourceManager.GetString("you_have_already_paired_using_this_vin", resourceCulture);
            }
        }
        
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        internal static string continue_text {
            get {
                return ResourceManager.GetString("continue_text", resourceCulture);
            }
        }
        
        internal static string doneButton {
            get {
                return ResourceManager.GetString("doneButton", resourceCulture);
            }
        }
        
        internal static string resetButton {
            get {
                return ResourceManager.GetString("resetButton", resourceCulture);
            }
        }
        
        internal static string select_model {
            get {
                return ResourceManager.GetString("select_model", resourceCulture);
            }
        }
        
        internal static string invalid_vin {
            get {
                return ResourceManager.GetString("invalid_vin", resourceCulture);
            }
        }
        
        internal static string device_connecting_error {
            get {
                return ResourceManager.GetString("device_connecting_error", resourceCulture);
            }
        }
        
        internal static string device_pairing_error {
            get {
                return ResourceManager.GetString("device_pairing_error", resourceCulture);
            }
        }
        
        internal static string device_connecting_error_title {
            get {
                return ResourceManager.GetString("device_connecting_error_title", resourceCulture);
            }
        }
        
        internal static string device_pairing_error_title {
            get {
                return ResourceManager.GetString("device_pairing_error_title", resourceCulture);
            }
        }
        
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        internal static string existing_device_title {
            get {
                return ResourceManager.GetString("existing_device_title", resourceCulture);
            }
        }
        
        internal static string existing_paired_device_error {
            get {
                return ResourceManager.GetString("existing_paired_device_error", resourceCulture);
            }
        }
        
        internal static string existing_accessory_gateway_error {
            get {
                return ResourceManager.GetString("existing_accessory_gateway_error", resourceCulture);
            }
        }
        
        internal static string battery_monitor_already_scanned {
            get {
                return ResourceManager.GetString("battery_monitor_already_scanned", resourceCulture);
            }
        }
        
        internal static string wind_sensor_already_scanned {
            get {
                return ResourceManager.GetString("wind_sensor_already_scanned", resourceCulture);
            }
        }
        
        internal static string all_wind_sensors_already_scanned {
            get {
                return ResourceManager.GetString("all_wind_sensors_already_scanned", resourceCulture);
            }
        }
        
        internal static string existing_battery_monitor_error {
            get {
                return ResourceManager.GetString("existing_battery_monitor_error", resourceCulture);
            }
        }
        
        internal static string reset_settings_title {
            get {
                return ResourceManager.GetString("reset_settings_title", resourceCulture);
            }
        }
        
        internal static string reset_settings_message {
            get {
                return ResourceManager.GetString("reset_settings_message", resourceCulture);
            }
        }
        
        internal static string rv {
            get {
                return ResourceManager.GetString("rv", resourceCulture);
            }
        }
        
        internal static string battery_monitor {
            get {
                return ResourceManager.GetString("battery_monitor", resourceCulture);
            }
        }
        
        internal static string wind_sensor {
            get {
                return ResourceManager.GetString("wind_sensor", resourceCulture);
            }
        }
        
        internal static string invalid_device_qr_code {
            get {
                return ResourceManager.GetString("invalid_device_qr_code", resourceCulture);
            }
        }
        
        internal static string missing_qr_keys {
            get {
                return ResourceManager.GetString("missing_qr_keys", resourceCulture);
            }
        }
        
        internal static string unrecognized_qr_code {
            get {
                return ResourceManager.GetString("unrecognized_qr_code", resourceCulture);
            }
        }
        
        internal static string skip {
            get {
                return ResourceManager.GetString("skip", resourceCulture);
            }
        }
        
        internal static string title_settings {
            get {
                return ResourceManager.GetString("title_settings", resourceCulture);
            }
        }
        
        internal static string error_logs_caps {
            get {
                return ResourceManager.GetString("error_logs_caps", resourceCulture);
            }
        }
        
        internal static string generating_log_file {
            get {
                return ResourceManager.GetString("generating_log_file", resourceCulture);
            }
        }
        
        internal static string sending_logs {
            get {
                return ResourceManager.GetString("sending_logs", resourceCulture);
            }
        }
        
        internal static string unable_to_send {
            get {
                return ResourceManager.GetString("unable_to_send", resourceCulture);
            }
        }
        
        internal static string upload_complete {
            get {
                return ResourceManager.GetString("upload_complete", resourceCulture);
            }
        }
        
        internal static string upload_logs {
            get {
                return ResourceManager.GetString("upload_logs", resourceCulture);
            }
        }
        
        internal static string incomplete_configuration {
            get {
                return ResourceManager.GetString("incomplete_configuration", resourceCulture);
            }
        }
        
        internal static string your_configuration_is_incomplete {
            get {
                return ResourceManager.GetString("your_configuration_is_incomplete", resourceCulture);
            }
        }
        
        internal static string change_log_level {
            get {
                return ResourceManager.GetString("change_log_level", resourceCulture);
            }
        }
        
        internal static string events_below_this_level {
            get {
                return ResourceManager.GetString("events_below_this_level", resourceCulture);
            }
        }
        
        internal static string log_level {
            get {
                return ResourceManager.GetString("log_level", resourceCulture);
            }
        }
    }
}
